//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalKist.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public issue()
        {
            this.fines = new HashSet<fine>();
        }
    
        public int Id { get; set; }
        public string issueID { get; set; }
        public string memid { get; set; }
        public string bookid { get; set; }
        public string staffid { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<System.DateTime> refurndate { get; set; }
        public Nullable<System.DateTime> returneddate { get; set; }
    
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fine> fines { get; set; }
        public virtual member member { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
